/* Creative community extension. Public projects; private owner-scoped Vault. */
const PV=(()=>{
 const state={posts:[],saves:[],collections:[],user:null,db:null,remix:null,pending:new Set(),unsub:[],vaultTab:'saved',collection:'all',profile:null};
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n;};
 const btn=(text,fn,primary=false)=>{const b=el('button',text,'pv-button'+(primary?' primary':''));b.addEventListener('keydown',e=>e.stopPropagation());b.type='button';b.onclick=e=>{e.stopPropagation();fn();};return b;};
 const url=v=>{try{const u=new URL(v);return u.protocol==='https:'?u.href:null;}catch{return null;}};
 const notice=m=>{if(typeof showToast==='function')showToast(m);else alert(m);};
 const link=(text,href)=>{const a=el('a',text);a.href=href;return a;};
 const postLink=p=>'index.html?project='+encodeURIComponent(p.id)+'#prompts';
 function normalized(p){return {...p,text:typeof p.text==='string'?p.text:typeof p.prompt==='string'?p.prompt:'',tags:Array.isArray(p.tags)?p.tags.filter(x=>typeof x==='string'):[],referenceImages:Array.isArray(p.referenceImages)?p.referenceImages.filter(x=>typeof x==='string'):[],mediaUrl:p.mediaUrl||p.preview?.url};}
 function getPosts(){if(state.posts.length)return state.posts;try{return FEED.map(normalized);}catch{return [];}}
 function count(id){return getPosts().filter(p=>p.remixOf===id).length;}
 function requireUser(){if(state.user)return true;notice('Sign in to save or publish. Your remix can be edited and copied without signing in.');if(typeof openAuthModal==='function')openAuthModal();else if(typeof signInWithGoogle==='function')signInWithGoogle();return false;}
 function dialog(title){const d=el('dialog',undefined,'pv-dialog');const close=btn('×',()=>d.close());close.className='pv-close';close.setAttribute('aria-label','Close');d.append(close,el('h2',title));d.addEventListener('close',()=>d.remove());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});document.body.append(d);return d;}
 function tags(p){const row=el('div',undefined,'pv-tags');if(p.tool)row.append(el('span',p.tool));for(const t of (Array.isArray(p.tags)?p.tags:[]))row.append(el('span','#'+t));return row;}
 function credit(p){const n=el('div',undefined,'pv-credit');if(p.remixOf){n.append('Remixed from ',link(p.remixSourceTitle||'original project',postLink({id:p.remixOf})),' by ',link(p.remixAuthorName||'original creator','profile.html?u='+encodeURIComponent(p.remixAuthorId||'')));}return n;}
 function actions(p){const row=el('div',undefined,'pv-actions');row.addEventListener('click',e=>e.stopPropagation());row.addEventListener('keydown',e=>e.stopPropagation());const remix=btn('↗ Remix · '+count(p.id),()=>openRemix(p),true);remix.setAttribute('aria-label','Remix '+p.title);row.append(remix);const saved=state.saves.some(s=>s.promptId===p.id);const save=btn(saved?'Saved ✓':'Save',()=>savePicker(p));save.disabled=state.pending.has(p.id);row.append(save,btn('Share',async()=>{const href=new URL(postLink(p),location.href).href;try{if(navigator.share)await navigator.share({title:p.title,url:href});else{await navigator.clipboard.writeText(href);notice('Project link copied.');}}catch(e){if(e.name!=='AbortError')notice('Could not share. Copy the page link instead.');}}));return row;}
 function openDetail(raw){const p=normalized(raw),d=dialog(p.title);d.append(el('p',p.category+' · '+(p.authorName||'Community member'),'pv-note'));if(p.authorId)d.append(link('View '+p.authorName+"'s profile",'profile.html?u='+encodeURIComponent(p.authorId)));if(url(p.mediaUrl)){const m=el(p.mediaType==='video'?'video':'img');m.src=url(p.mediaUrl);m.alt=p.title;if(p.mediaType==='video'){m.controls=true;m.style.width='100%';}d.append(m);}if(p.description)d.append(el('p',p.description,'pv-desc'));d.append(tags(p));if(p.remixOf)d.append(credit(p));d.append(el('h3','Original prompt'));const text=el('p',p.text);text.style.whiteSpace='pre-wrap';d.append(text);if(p.processNotes){d.append(el('h3','Process notes'),el('p',p.processNotes,'pv-desc'));}for(const r of (p.referenceImages||[])){if(url(r)){const image=el('img');image.src=url(r);image.alt='Reference image';image.loading='lazy';d.append(image);}}d.append(actions(p),btn('Copy prompt',()=>copy(p.text)));d.showModal();}
 async function copy(text){try{await navigator.clipboard.writeText(text);notice('Prompt copied.');}catch{notice('Select the prompt text and copy it.');}}
 function openRemix(raw){const p=normalized(raw),d=dialog('Make it yours');d.append(el('p','Remix '+p.title,'pv-desc'),el('div',undefined,'pv-credit'));const c=d.querySelector('.pv-credit');c.append('Original by ',link(p.authorName||'Community member','profile.html?u='+encodeURIComponent(p.authorId||'')),'. Your published remix will link back to this project.');d.append(tags(p));const vars=el('div',undefined,'pv-variables');const inputs={};for(const key of ['subject','style','colors','mood']){const group=el('div');group.append(el('label',key[0].toUpperCase()+key.slice(1)));const i=el('input');i.placeholder='New '+key;i.maxLength=120;group.append(i);inputs[key]=i;vars.append(group);}d.append(vars,el('label','Customize the prompt'));const t=el('textarea');t.value=p.text;t.maxLength=20000;t.setAttribute('aria-label','Customize the prompt');d.append(t,el('p','Use {subject}, {style}, {colors}, {mood} in your text, or add the variables as directions. Nothing is published until you review and submit the Create form.','pv-note'));d.append(btn('Apply variables',()=>{let value=t.value;for(const [key,i]of Object.entries(inputs)){if(!i.value.trim())continue;const token='{'+key+'}';value=value.includes(token)?value.split(token).join(i.value.trim()):value+'\n'+key[0].toUpperCase()+key.slice(1)+': '+i.value.trim();}t.value=value;}),el('div',undefined,'pv-actions'));const row=d.querySelector('.pv-actions');row.append(btn('Copy remix',()=>copy(t.value)),btn('Continue to Create',()=>{if(!t.value.trim()){notice('Add your prompt first.');return;}sessionStorage.setItem('pvRemixDraft',JSON.stringify({id:p.id,title:p.title,authorId:p.authorId,authorName:p.authorName,text:t.value,category:p.category,tool:p.tool||'',tags:p.tags||[]}));d.close();if(location.pathname.endsWith('/community.html')){loadDraft();document.getElementById('postForm').scrollIntoView({behavior:'smooth'});}location.href='community.html?create=1#postForm';},true));d.showModal();}
 async function savePicker(p){if(!requireUser())return;const d=dialog('Save to My Vault');d.append(el('p',p.title,'pv-desc'));const label=el('label','Collection');const select=el('select');const all=el('option','Unsorted');all.value='';select.append(all);for(const c of state.collections){const o=el('option',c.name);o.value=c.id;select.append(o);}const saved=state.saves.find(s=>s.promptId===p.id);select.value=saved?.collectionId||'';d.append(label,select);const error=el('p','','pv-note pv-error');d.append(error);d.append(btn('Save project',async()=>{if(state.pending.has(p.id))return;state.pending.add(p.id);try{await state.db.collection('saves').doc(state.user.uid+'_'+p.id).set({uid:state.user.uid,promptId:p.id,collectionId:select.value,createdAt:firebase.firestore.FieldValue.serverTimestamp()});d.close();notice('Saved to My Vault.');}catch{error.textContent='Save failed. The updated database rules must be enabled. Nothing was saved.';}finally{state.pending.delete(p.id);enhance();}},true));if(saved)d.append(btn('Remove from Vault',async()=>{try{await state.db.collection('saves').doc(saved.id).delete();d.close();notice('Removed from Vault.');}catch{error.textContent='Could not remove this save. Try again.';}}));d.append(btn('New collection',()=>collectionDialog()));d.showModal();}
 function collectionDialog(){if(!requireUser())return;const d=dialog('New collection'),name=el('input');name.placeholder='Branding Ideas';name.maxLength=80;name.setAttribute('aria-label','Collection name');const error=el('p','','pv-note pv-error');d.append(name,error,btn('Create collection',async()=>{if(!name.value.trim()){error.textContent='Give your collection a name.';return;}try{await state.db.collection('collections').add({uid:state.user.uid,name:name.value.trim(),createdAt:firebase.firestore.FieldValue.serverTimestamp()});d.close();notice('Collection created. Reopen Save to choose it.');}catch{error.textContent='Could not create the collection. Updated database rules are required.';}},true));d.showModal();}
 function metadata(p){const n=el('div',undefined,'pv-enhancement');if(p.description)n.append(el('p',p.description,'pv-desc'));n.append(tags(p));if(p.remixOf)n.append(credit(p));n.append(actions(p),btn('View project',()=>openDetail(p)));return n;}
 function enhance(){for(const [selector,posts]of [['#promptGrid .prompt-card',getPosts()],['#communityFeed .community-card',getPosts()],['#profileFeed .profile-tile',getPosts()]]){document.querySelectorAll(selector).forEach(card=>{const title=card.querySelector('h3')?.textContent;const p=posts.find(x=>x.id===card.dataset.projectId);if(!p)return;if(card.tagName==='BUTTON')return;const stamp=JSON.stringify([p,state.saves.map(s=>s.promptId),count(p.id),state.pending.has(p.id)]);if(card.dataset.pvStamp===stamp)return;card.dataset.pvStamp=stamp;card.querySelector('.pv-enhancement')?.remove();card.append(metadata(p));if(selector.includes('community')){const m=card.querySelector('.community-media');if(m)card.prepend(m);}});}renderVault();renderProfileExtra();}
 function postData(){const v=id=>document.getElementById(id)?.value.trim()||'';const data={description:v('postDescription'),tool:v('postTool'),tags:[...new Set(v('postTags').split(',').map(x=>x.trim()).filter(Boolean))].slice(0,8).map(x=>x.slice(0,30)),processNotes:v('postNotes'),referenceImages:v('postRefs').split('\n').map(x=>url(x.trim())).filter(Boolean).slice(0,4)};if(state.remix)Object.assign(data,{remixOf:state.remix.id,remixAuthorId:state.remix.authorId,remixAuthorName:state.remix.authorName,remixSourceTitle:state.remix.title});return data;}
 function clearRemix(){state.remix=null;sessionStorage.removeItem('pvRemixDraft');const c=document.getElementById('remixCredit');if(c){c.hidden=true;c.replaceChildren();}}
 function loadDraft(){if(!document.getElementById('postForm'))return;try{const draft=JSON.parse(sessionStorage.getItem('pvRemixDraft')||'null');if(!draft)return;state.remix=draft;document.getElementById('postTitle').value='Remix: '+draft.title;document.getElementById('postText').value=draft.text;document.getElementById('postCategory').value=draft.category;document.getElementById('postTool').value=draft.tool;document.getElementById('postTags').value=draft.tags.join(', ');const c=document.getElementById('remixCredit');c.hidden=false;c.append('Remixing ',link(draft.title,postLink(draft)),' by '+draft.authorName,btn('Start fresh',()=>{clearRemix();document.getElementById('postForm').reset();}));}catch{clearRemix();}}
 function nav(){const n=el('nav',undefined,'pv-nav');n.setAttribute('aria-label','Main navigation');const page=location.pathname.split('/').pop();for(const [title,icon,href]of [['Discover','▧','index.html#prompts'],['Create','+','community.html?create=1#postForm'],['My Vault','◇','vault.html']]){const a=link('',href);a.append(el('span',icon),document.createTextNode(title));if((page===href.split(/[?#]/)[0])){a.className='active';a.setAttribute('aria-current','page');}n.append(a);}const b=btn('Profile',()=>{if(requireUser())location.href='profile.html?u='+encodeURIComponent(state.user.uid);});b.prepend(el('span','◯'));b.setAttribute('aria-label','Profile');if(page==='profile.html')b.className='active';n.append(b);document.body.append(n);}
 function renderVault(){const root=document.getElementById('vaultContent');if(!root)return;root.replaceChildren();if(!state.user){root.append(el('div','Your private creative library. Sign in to save projects, create collections and see your contributions.','pv-empty'),btn('Continue with Google',()=>signInWithGoogle(),true));return;}root.append(el('p','Welcome, '+(state.user.displayName||'creator')+'. Only you can read your saves and collections.','pv-desc'));const tabs=el('div',undefined,'pv-tabs');for(const [key,title]of [['saved','Saved projects'],['posts','My projects'],['remixes','My remixes'],['creators','Favorite creators']]){const b=btn(title,()=>{state.vaultTab=key;renderVault();});if(state.vaultTab===key)b.classList.add('active');tabs.append(b);}root.append(tabs);if(state.vaultTab==='creators'){root.append(el('p','Creators you follow','pv-note'));state.db.collection('follows').where('followerId','==',state.user.uid).get().then(s=>{for(const doc of s.docs){const id=doc.data().followeeId;const p=getPosts().find(p=>p.authorId===id);root.append(link(p?.authorName||'View creator','profile.html?u='+encodeURIComponent(id)),el('br'));}if(!s.size)root.append(el('div','Follow a creator from their profile to keep them here.','pv-empty'));}).catch(()=>root.append(el('p','Could not load your followed creators.')));return;}
 if(state.vaultTab==='saved'){const filter=el('select');filter.setAttribute('aria-label','Filter collection');for(const [id,name]of [['all','All collections'],['','Unsorted'],...state.collections.map(c=>[c.id,c.name])]){const o=el('option',name);o.value=id;filter.append(o);}filter.value=state.collection;filter.onchange=()=>{state.collection=filter.value;renderVault();};root.append(filter,btn('New collection',collectionDialog));if(state.collection&&state.collection!=='all')root.append(btn('Delete collection',async()=>{if(!confirm('Delete this collection? Its projects will remain saved in Unsorted.'))return;try{const batch=state.db.batch();state.saves.filter(s=>s.collectionId===state.collection).forEach(s=>batch.update(state.db.collection('saves').doc(s.id),{collectionId:''}));batch.delete(state.db.collection('collections').doc(state.collection));await batch.commit();state.collection='all';}catch{notice('Could not delete collection. Try again.');}}));}
 const grid=el('div',undefined,'pv-grid');let posts=state.vaultTab==='saved'?state.saves.filter(s=>state.collection==='all'||s.collectionId===state.collection).map(s=>getPosts().find(p=>p.id===s.promptId)||{id:s.promptId,title:'Project no longer available',text:''}):getPosts().filter(p=>p.authorId===state.user.uid&&(state.vaultTab!=='remixes'||p.remixOf));for(const p of posts){const card=el('article',undefined,'pv-saved');if(url(p.mediaUrl)&&p.mediaType==='image'){const img=el('img');img.src=url(p.mediaUrl);img.alt=p.title;card.append(img);}card.append(el('h3',p.title),metadata(p));grid.append(card);}if(!posts.length)grid.append(el('div',state.vaultTab==='saved'?'Nothing saved yet. Explore Discover and save something that inspires you.':'Your projects will appear here after you publish.','pv-empty'));root.append(grid);}
 function renderProfileExtra(){const uid=new URLSearchParams(location.search).get('u');if(!uid||!document.getElementById('profileFeed'))return;let box=document.getElementById('pvProfileExtra');if(!box){box=el('section',undefined,'pv-profile-bio');box.id='pvProfileExtra';document.getElementById('profileFeed').before(box);}box.replaceChildren();if(state.profile){if(state.profile.bio)box.append(el('p',state.profile.bio));if(state.profile.specialties)box.append(el('p',state.profile.specialties,'pv-note'));}box.append(el('p',getPosts().filter(p=>p.authorId===uid&&p.remixOf).length+' published remixes','pv-note'));if(state.user?.uid===uid)box.append(btn('Edit bio & specialties',editProfile),link('Private collections and saved work','vault.html'));for(const post of getPosts().filter(p=>p.authorId===uid&&state.profile?.featuredIds?.includes(p.id))){box.append(el('h3','Featured: '+post.title),btn('View featured project',()=>openDetail(post)));}}
 function editProfile(){const d=dialog('Your creative identity');d.append(el('label','Bio'));const bio=el('textarea');bio.className='pv-small';bio.maxLength=500;bio.value=state.profile?.bio||'';d.append(bio,el('label','Design specialties'));const spec=el('input');spec.maxLength=160;spec.value=state.profile?.specialties||'';d.append(spec,el('label','Featured project'));const select=el('select');const empty=el('option','None');empty.value='';select.append(empty);for(const p of getPosts().filter(p=>p.authorId===state.user.uid)){const o=el('option',p.title);o.value=p.id;select.append(o);}select.value=state.profile?.featuredIds?.[0]||'';const err=el('p','','pv-note pv-error');d.append(select,err,btn('Save profile',async()=>{try{await state.db.collection('profiles').doc(state.user.uid).set({uid:state.user.uid,bio:bio.value.trim(),specialties:spec.value.trim(),featuredIds:select.value?[select.value]:[]});d.close();}catch{err.textContent='Profile not saved. Updated rules are required.';}},true));d.showModal();}
 function subscribeUser(user){state.unsub.forEach(f=>f());state.unsub=[];state.user=user;state.saves=[];state.collections=[];if(user){for(const name of ['saves','collections'])state.unsub.push(state.db.collection(name).where('uid','==',user.uid).onSnapshot(s=>{state[name]=s.docs.map(d=>({id:d.id,...d.data()}));enhance();},()=>{const root=document.getElementById('vaultStatus');if(root)root.textContent='Private Vault could not load. Enable the updated database rules and refresh.';}));}enhance();}
 function init(){nav();loadDraft();if(typeof openPromptModal==='function')openPromptModal=id=>{const p=getPosts().find(x=>x.id===id);if(p)openDetail(p);};if(typeof openPrompt==='function')openPrompt=p=>openDetail(p);if(!firebase.apps.length)return;state.db=firebase.firestore();firebase.auth().onAuthStateChanged(subscribeUser);state.db.collection('prompts').orderBy('createdAt','desc').onSnapshot(s=>{state.posts=s.docs.map(d=>normalized({id:d.id,...d.data()}));enhance();const id=new URLSearchParams(location.search).get('project');if(id&&!window.pvProjectOpened){const p=getPosts().find(p=>p.id===id);if(p){window.pvProjectOpened=true;openDetail(p);}}},()=>{});const uid=new URLSearchParams(location.search).get('u');if(uid)state.db.collection('profiles').doc(uid).onSnapshot(s=>{state.profile=s.exists?s.data():null;renderProfileExtra();},()=>{});const observer=new MutationObserver(list=>{if(list.some(x=>x.addedNodes.length&&Array.from(x.addedNodes).some(n=>n.nodeType===1&&(n.matches?.('.prompt-card,.community-card,.profile-tile')))))enhance();});for(const id of ['promptGrid','communityFeed','profileFeed']){const n=document.getElementById(id);if(n)observer.observe(n,{childList:true});}enhance();}
 document.addEventListener('DOMContentLoaded',init);
 return {postData,clearRemix,openRemix,openDetail,state,enhance};
})();
